version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8765:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    restart: always
    volumes:
      - ./sql/data.sql:/technology-mysql/data.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'technology'
      MYSQL_USER: 'technology'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

